### PR TITLE
 Make getMatches(final double[] vec, int maxNumMatches) public #6 

### PR DESCRIPTION
**Pull request by guerda**
Makes SearcherImpl.getMatches(double[], int) public and exposes it to the interface for matching words by a given vector.

### CODE REVIEW

**Comment by yibinlin** [comment]
Hi @guerda That seems fine. Would you mind adding a test in Word2VecTest.java about this newly exposed functionality? E.g. it can be something similar to Word2VecTest.testSearch() with input vector other than word.

**Comment by guerda** [comment]
Hi @yibinlin ! Thanks for the feedback! Of course, I will add one or two unit tests. I will push the changes on this branch, so that it will appear in this PR.

**Comment by guerda** [comment]
Hi @yibinlin !
I added a test case for the now public method. Seems fine on Travis.

**Comment by yibinlin** [comment]
@guerda Looks great! Merging it.

Thanks Philip!

**Pull request merged**
